import { Injectable } from '@angular/core';
import { CategorySlug, ManifestEntry } from '../shared/manifest.model';

import portraits from '../manifests/portraits.json';
import modeling from '../manifests/modeling.json';
import sports from '../manifests/sports.json';
import street from '../manifests/street.json';
import products from '../manifests/products.json';
import graduation from '../manifests/graduation.json';
import aesthetics from '../manifests/aesthetics.json';
import hero from '../manifests/hero.json';
import about from '../manifests/about.json';

/**
 * Central access point for the bundle-imported image manifests generated by
 * scripts/build_image_pipeline.py. Manifests are static JSON imports so they
 * ship with the JS bundle (no runtime fetch).
 */
@Injectable({ providedIn: 'root' })
export class ManifestService {
  private map: Record<CategorySlug | 'hero' | 'about', ManifestEntry[]> = {
    portraits: portraits as ManifestEntry[],
    modeling: modeling as ManifestEntry[],
    sports: sports as ManifestEntry[],
    street: street as ManifestEntry[],
    products: products as ManifestEntry[],
    graduation: graduation as ManifestEntry[],
    aesthetics: aesthetics as ManifestEntry[],
    hero: hero as ManifestEntry[],
    about: about as ManifestEntry[],
  };

  get(category: CategorySlug | 'hero' | 'about'): ManifestEntry[] {
    return this.map[category] ?? [];
  }

  /** First image in a category — used as the featured / card image. */
  featured(category: CategorySlug | 'hero' | 'about'): ManifestEntry | undefined {
    return this.get(category)[0];
  }

  /** Look up a specific entry by its id (image filename stem). */
  findById(category: CategorySlug | 'hero' | 'about', id: string): ManifestEntry | undefined {
    return this.get(category).find(e => e.id === id);
  }
}
